# Configurações de Conexão com o Banco de Dados PostgreSQL
# Disciplina: ADS1253 - POO com Banco de Dados
db.url=jdbc:postgresql://localhost:5432/sistema_vendas
db.user=postgres
db.password=28072006
db.driver=org.postgresql.Driver
